# Copyright 2014 Makepolo Inc. All Rights Reserved.
# Author: huangyue@makepolo.com (Yue Huang)

cc_library(
    name = 'rpc_channel.h',
    deps = [
           '//util/bifrost/internal:rpc_channel_internal',
           ],
)

cc_library(
    name = 'blocking_socket',
    deps = [
           '//util/bifrost/internal:blocking_socket_internal',
           ],
)

cc_library(
    name = 'framed_transport',
    deps = [
           '//util/bifrost/internal:framed_transport_internal',
           ],
)

cc_library(
    name = 'read_buffer_transport',
    deps = [
           '//util/bifrost/internal:read_buffer_transport_internal',
           ],
)

cc_library(
    name = 'controller',
    deps = [
           '//util/bifrost/internal:controller_internal',
           ],
)

cc_library(
    name = 'nonblocking_server',
    deps = [
           '//util/bifrost/internal:nonblocking_server_internal',
           ],
)

cc_library(
    name = 'bifrost',
    deps = [
           '//util/bifrost/internal:bifrost_internal',
           ],
)

cc_library(
    name = 'request_parser',
    deps = [
           '//util/bifrost/internal:request_parser_internal',
           ],
)
