# Copyright 2014 Makepolo Inc. All Rights Reserved.
# Author: huangyue@makepolo.com (Yue Huang)

cc_test(
    name = 'blocking_socket_unittest',
    srcs = [
           'blocking_socket_unittest.cc',
           ],
    deps = [
           '//base:base',
           '//util/bifrost/public:blocking_socket',
           ],
)
